In [1]:
import os

os.getcwd()

'C:\\Users\\Tushar Gajbhiye\\Downloads'

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '101025ET07309356.pdf',
 '10OCT2025.pdf',
 '24042026174809666122.pdf',
 '25112899902001 (1).pdf',
 '25112899902001 (2).pdf',
 '25112899902001 (3).pdf',
 '4341XXXXXXXXXX35_18-01-2026_604.pdf',
 '6th Nov - Mukki Permit-Evening.pdf',
 '6th Nov - Mukki Permit.pdf',
 '7th Nov - Kanha Permit.pdf',
 'access_log.txt',
 'Acko-20260115-6cbdc03a-842d-46bd-b799-cb03d242b89f_260115_185450.pdf',
 'ADF interview questions.docx',
 'ADITYA BIRLA SUN LIFE LIQUID FUND.xlsx',
 'Anaconda3-2026.07-1-Windows-x86_64.exe',
 'Application Details - V8.0.docx',
 'Application_details_v_180725.xlsx',
 'AppointmentReciept.pdf',
 'archive (1).zip',
 'archive.zip',
 'Autogramm Bitte.pdf',
 'Azure Data Engineering+ADF+SQL (1).docx',
 'B5-702 Majestique Signature Towers PVC.pdf',
 'book.txt',
 'ChromeSetup.exe',
 'companies_report.ipynb',
 'companies_report.py',
 'config.share',
 'Consolidated EoI Evaluation sheet_30122025_V1.xlsx',
 'Copy of P6-UK-Bank-Customers_14march2025.csv',
 'craete_table_syntax',
 'credential-ob3-c355566d-3c9b-4980-8511-93c84d05c374.json',
 'dab_demo_notebook.ipynb',
 'databricks-Serverless Starter Warehouse.pbids',
 'databricks.yml',
 'dea05-databricks-jobs.dbc',
 'debug.log',
 'desktop.ini',
 'Docker Desktop Installer.exe',
 'EAadhaar_0638207250055620220418105213_12022026225928.pdf',
 'epfo_withdrawal.pdf',
 'Farben worksheet.pdf',
 'forest.mponline.gov.in_Cancelation_TicketCancelRecipt.aspx_TicketID=24M261950934.pdf',
 'forest.mponline.gov.in_Cancelation_TicketCancelRecipt.aspx_TicketID=25E261950945.pdf',
 'forest.mponline.gov.in_Cancelation_TicketCancelRecipt.aspx_TicketID=25M261950925.pdf',
 "G163326740_Invoice - May'26.pdf",
 "G169874530_Invoice - June'26.pdf",
 'generate_data.py',
 'gizmobox_data.zip',
 'Gruppe A Berufe.pdf',
 'Gruppe B Berufe.pdf',
 'Hausaufagben Woche 1 (1).pdf',
 'Hausaufagben Woche 1.pdf',
 'ICICI - Statement_NOV2025_013322588.pdf',
 'jdk-21_windows-x64_bin.exe',
 'jdk-27',
 'jdk-27_windows-x64_bin.zip',
 'Kap 3.pdf',
 'KB Übungen .pdf',
 'Klassengegenstände Partner A.pdf',
 'Kryterion Purchase Receipt - 29 July 2026 (1).pdf',
 'Kryterion Purchase Receipt - 29 July 2026.pdf',
 'Leave and License SHALU PANDIT_260212_233437.pdf',
 'Marvel+Graph',
 'Marvel+Names',
 'meeting-82542892495.ics',
 'Mit Deutsch bin ich so global-Liedtext-2.pdf',
 'ml-100k.zip',
 'Modalverben Blatt.pdf',
 'Most Important Terms & Conditions (1).pdf',
 'Most Important Terms & Conditions.pdf',
 'most-popular-superhero-dataframe.py',
 'mögen Was essen sie.pdf',
 'MrsApurva.pdf',
 'MV HA.pdf',
 'Non Text Magic Studio Magic Design for Presentations L&P.pdf',
 'npp.8.9.7.Installer.x64.exe',
 'offline_orders.csv',
 'Online Application Receipt (1).pdf',
 'Online Application Receipt.pdf',
 'online_customers.csv',
 'online_products.csv',
 'orders.csv',
 'Ordinalzahlen Liste.pdf',
 'Orte Arbeitsblatt.pdf',
 'P6-UK-Bank-Customers.csv',
 'Pluralformen- Hausaufgabe (1).pdf',
 'Pluralformen- Hausaufgabe.pdf',
 'Possessiveartikel- Wiederholung.pdf',
 'Präteritum AB 1.pdf',
 'Präteritum AB 2.pdf',
 'python-3.11.9-amd64.exe',
 'Quote (14) (13).pdf',
 'Ram singh Pune Shine_260412_190645.pdf',
 'RFP GIS-reviewed.pdf',
 'shanivar wada.webp',
 'Stadt Festigung.pdf',
 'Tag 1 Blatt.pdf',
 'Tag 2 Blatt-2.pdf',
 'Tag 3 Blatt.pdf',
 'top_tech_companies_data.zip',
 'tsetup-x64.7.0.9.exe',
 'tushar passport application.pdf',
 'Tushar_Gajbhiye_Data_Engineer_Resume_Revised.docx',
 'Uhrzeiten Arbeitsblatt + HA-2 (1).pdf',
 'Uhrzeiten Arbeitsblatt + HA-2.pdf',
 'ULMS Vendor Evaluation.pptx',
 'UltraViewer_setup_6.6.124_en.exe',
 'Unified Land Management System - SCDLR_EoI_V1_260128_190949.pdf',
 'unregelmäßige Verben Wiederholung.pdf',
 'Untitled.ipynb',
 'VSCodeUserSetup-x64-1.122.1.exe',
 'VW TERMS AND CONDITION (3).pdf',
 'Wer sagt was- Pdf.pdf',
 'Wer sagt was.pdf',
 'WhatsApp Image 2026-06-21 at 20.09.40.jpeg',
 'Wiederholung Kap 1-4 Abend OLU (1).pdf',
 'Wiederholung Kap 1-4 Abend OLU.pdf']

In [12]:
import pandas as pd

df = pd.read_csv('orders.csv', na_values=['Not Available','unknown']) #whatever values are passed they will be treated as NULLs
df['Ship Mode'].unique()

<ArrowStringArray>
['Second Class', 'Standard Class', nan, 'First Class', 'Same Day']
Length: 5, dtype: str

In [10]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [6]:
df.shape

(9994, 16)

In [7]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='str')

In [8]:
df.dtypes

Order Id            int64
Order Date            str
Ship Mode             str
Segment               str
Country               str
City                  str
State                 str
Postal Code         int64
Region                str
Category              str
Sub Category          str
Product Id            str
cost price          int64
List Price          int64
Quantity            int64
Discount Percent    int64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   str
 2   Ship Mode         9993 non-null   str
 3   Segment           9994 non-null   str
 4   Country           9994 non-null   str
 5   City              9994 non-null   str
 6   State             9994 non-null   str
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   str
 9   Category          9994 non-null   str
 10  Sub Category      9994 non-null   str
 11  Product Id        9994 non-null   str
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), str(10)
memory usage: 2.2 MB

In [13]:
df['Ship Mode'].unique() #'Not Available','unknown' - are 'nan' values

<ArrowStringArray>
['Second Class', 'Standard Class', nan, 'First Class', 'Same Day']
Length: 5, dtype: str

In [23]:
#rename column names & make them lower case and replace space with underscore
#df.rename(columns={'Order Id':'order_id', 'City':'city'}) #to change into; but this isn't feasible for many number of columns

#df.columns #gives a list of columns
#df.columns.str.lower() #would make all the column names into lower case
#df.columns = df.columns.str.lower()
#df.columns.str.replace(' ','_')#will replace spaces into _
#df.columns = df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [30]:
#derive new columns - discount, sale price and profit
#df['list_price']*df['discount_percent']*0.01 #(divide by 100 equivalent) 
#df['discount'] = df['list_price']*df['discount_percent']*0.01 #would create a new column -'discount'
#df['sale_price'] = df['list_price']-df['discount'] #mrp-discount
#df['profit'] = df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [36]:
#convert order date from object data type to datetime
#df.dtypes
#pd.to_datetime(df['order_date'], format='%Y-%m-%d') #would convert column order_date into date, using format
#df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')
df.dtypes

order_id                     int64
order_date          datetime64[us]
ship_mode                      str
segment                        str
country                        str
city                           str
state                          str
postal_code                  int64
region                         str
category                       str
sub_category                   str
product_id                     str
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [41]:
#drop columns - cost price, list price and discount percent
df.drop(columns=['cost_price','list_price','discount_percent']) #inplace would actually remove from dataset
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [42]:
import sqlalchemy as sal
import pyodbc

engine = sal.create_engine(
    "mssql+pyodbc://localhost/PracticeDB"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&Trusted_Connection=yes"
    "&TrustServerCertificate=yes"
)

conn = engine.connect()

print("Connected successfully!")

Connected successfully!

In [44]:
#Load the data into sql server using append option
#df.to_sql('df_orders', con=conn, index=False, if_exists = 'replace')
#Try not to use this option as Pandas try to create wiith highest datatypes like varchar(max), bigint etc.Instead
#try to create a table with option using 'append' inplace of 'replace';

38

In [45]:
conn.commit() #permanently saves the work

In [48]:
df.to_sql('df_orders', con=conn, index=False, if_exists = 'append')

38

In [46]:
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM dbo.df_orders",
    conn
)

   row_count
0       9994

In [49]:
conn.commit()

In [50]:
pd.read_sql(
    "SELECT COUNT(*) AS row_count FROM dbo.df_orders",
    conn
)

   row_count
0       9994

In [47]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='str')

In [43]:
query = "SELECT * FROM Employees"

df_sql = pd.read_sql(query, conn)

df_sql

   EmployeeID   Name Department  Salary
0           1  Rahul         IT   60000
1           2  Priya    Finance   70000
2           3   Amit         HR   55000
3           4  Sneha         IT   75000
4           5  Rohan    Finance   65000